# Generated by Django 6.0.8 on 2026-08-07 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_id', models.CharField(max_length=64)),
                ('tier', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('moderating', 'Moderating'), ('factchecking', 'Fact-checking'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('raw_title', models.TextField(blank=True)),
                ('raw_paragraphs', models.JSONField(blank=True, default=list)),
                ('raw_alarmism', models.FloatField(blank=True, null=True)),
                ('moderated_title', models.TextField(blank=True)),
                ('moderated_paragraphs', models.JSONField(blank=True, default=list)),
                ('moderated_alarmism', models.FloatField(blank=True, null=True)),
                ('emotive_spans', models.JSONField(blank=True, default=list)),
                ('factual_check', models.JSONField(blank=True, default=list)),
                ('human_text', models.TextField(blank=True)),
                ('human_title', models.CharField(blank=True, max_length=300)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset_id', 'tier', 'status'], name='storytellin_dataset_18fa54_idx')],
            },
        ),
        migrations.CreateModel(
            name='StageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('generate', 'Generate'), ('moderate', 'Moderate'), ('factcheck', 'Fact-check'), ('judge_raw', 'Judge (raw)'), ('judge_moderated', 'Judge (moderated)')], max_length=24)),
                ('model', models.CharField(max_length=64)),
                ('duration_s', models.FloatField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='storytelling.run')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
