# Generated by Django 6.0.8 on 2026-08-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageresult',
            name='usage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
