# Generated by Django 6.0.8 on 2026-08-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0002_stageresult_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='human_alarmism',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
