# Generated by Django 6.0.8 on 2026-08-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0002_stageresult_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='opus_cost_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_moderated_alarmism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_raw_alarmism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageresult',
            name='stage',
            field=models.CharField(choices=[('generate', 'Generate'), ('moderate', 'Moderate'), ('factcheck', 'Fact-check'), ('judge_raw', 'Judge (raw)'), ('judge_moderated', 'Judge (moderated)'), ('judge_independent', 'Judge (independent, Claude CLI)')], max_length=24),
        ),
    ]
