# Generated by Django 6.0.8 on 2026-08-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0003_run_human_alarmism'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='opus_cost_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_moderated_alarmism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_raw_alarmism',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
