# Generated by Django 6.0.8 on 2026-08-11 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0003_run_opus_cost_usd_run_opus_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=500)),
                ('rows', models.IntegerField()),
                ('columns', models.JSONField(default=list)),
                ('numeric_columns', models.JSONField(default=list)),
                ('year_range', models.CharField(blank=True, max_length=32)),
                ('countries', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
