# Generated by Django 6.0.8 on 2026-08-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0004_uploadeddataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='moderated_optimism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_moderated_optimism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_raw_optimism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='raw_optimism',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
