# Generated by Django 6.0.8 on 2026-08-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0005_uploadeddataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='moderated_optimism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_moderated_optimism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='opus_raw_optimism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='raw_optimism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageresult',
            name='stage',
            field=models.CharField(choices=[('generate', 'Generate'), ('moderate', 'Moderate'), ('factcheck', 'Fact-check'), ('judge_raw', 'Judge (raw)'), ('judge_moderated', 'Judge (moderated)'), ('judge_independent', 'Judge (independent, Claude CLI)'), ('judge_opus_raw', 'Judge (Claude, raw)'), ('judge_opus_moderated', 'Judge (Claude, moderated)')], max_length=24),
        ),
    ]
