# Generated by Django 6.0.8 on 2026-08-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0006_run_moderated_optimism_run_opus_moderated_optimism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='human_optimism',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageresult',
            name='stage',
            field=models.CharField(choices=[('generate', 'Generate'), ('moderate', 'Moderate'), ('factcheck', 'Fact-check'), ('judge_raw', 'Judge (raw)'), ('judge_moderated', 'Judge (moderated)'), ('judge_independent', 'Judge (independent, Claude CLI)'), ('judge_opus_raw', 'Judge (Claude, raw)'), ('judge_opus_moderated', 'Judge (Claude, moderated)'), ('judge_opus_human', 'Judge (Claude, human baseline)')], max_length=24),
        ),
    ]
