# Generated by Django 6.0.8 on 2026-08-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0007_run_human_optimism_alter_stageresult_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=64)),
                ('n', models.PositiveSmallIntegerField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'model', 'n'), name='one_selection_per_source_model_n')],
            },
        ),
    ]
